apiVersion: v2
name: peaka
description: Helm chart of the best data integration platform, aka Peaka.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"
dependencies:
  - name: postgresql
    version: 13.4.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: minio
    version: ~5.1.0
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: mariadb-galera
    alias: mariadb
    version: 11.2.3
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: kafka
    version: 26.8.5
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: mongodb
    version: 14.8.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 18.11.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    alias: postgresqlbigtable
    version: 13.4.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresqlbigtable.enabled
  - name: temporal-operator
    alias: temporal
    version: 0.3.0
    repository: https://alexandrevilain.github.io/temporal-operator
    condition: temporal.enabled
