{{- if .Values.nfsServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-server
spec:
  ports:
    - name: nfs
      port: {{ .Values.nfsServer.servicePort }}
  selector:
    role: {{ include "peaka.fullname" . }}-nfs-server
{{- end -}}
