apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-share
  {{- if  .Values.nfsShare.volumeDeletionProtection }}
  annotations:
    helm.sh/resource-policy: "keep"
  {{- end }}
spec:
  capacity:
    storage: {{ .Values.nfsShare.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.nfsShare.path | quote }}
    server: {{ .Values.nfsServer.nfsServerAddress | default (printf "%s-nfs-server.%s.svc.cluster.local" (include "peaka.fullname" . ) .Release.Namespace ) }}
  persistentVolumeReclaimPolicy: {{ .Values.nfsShare.persistentVolumeReclaimPolicy }}
