{{- if .Values.nfsServer.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-server
  {{- if  .Values.nfsServer.persistentVolume.volumeDeletionProtection }}
  annotations:
    helm.sh/resource-policy: "keep"
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nfsServer.persistentVolume.size | quote }}
{{- end }}
