apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-share

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-share-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list", "create", "update"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "peaka.fullname" . }}-nfs-share-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "peaka.fullname" . }}-nfs-share
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "peaka.fullname" . }}-nfs-share-role
  apiGroup: rbac.authorization.k8s.io
