apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peaka.fullname" . }}-be-secret-store-service
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-secret-store-service
    {{- include "peaka.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.secretStoreService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-secret-store-service
      {{- include "peaka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-secret-store-service
        {{- include "peaka.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: secret-store-service
          image: "{{ include "peaka.image.registry" . }}/{{ .Values.secretStoreService.image.name }}:{{ .Values.secretStoreService.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.secretStoreService.image.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "peaka.fullname" . }}-env-config
          {{- with .Values.secretStoreService.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.secretStoreService.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.secretStoreService.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.secretStoreService.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.secretStoreService.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.secretStoreService.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
