{{- if .Values.connector.credentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peaka.fullname" . }}-connection-credentials-secret
type: Opaque
stringData:
  connection_providers.json: |
    {
      "sendgrid": {
        "apiKey": ""
      },
      "google": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret": ""
        }
      },
      "google_ads": {
        "clientInfo": {
          "type": "google_ads_oauth_client_info",
          "clientId": "",
          "clientSecret": "",
          "developerToken":""
        }
      },
      "hubspot": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret": ""
        }
      },
      "mailchimp": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret": ""
        }
      },
      "slack": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret": ""
        }
      },
      "intercom": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret": ""
        }
      },
      "stripe": {
        "apiKey": "",
        "endpointSecret": ""
      },
      "zoho_crm": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret": ""
        }
      },
      "linkedin": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret": ""
        }
      },
      "facebook": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret":""
         }
      },
      "pipedrive": {
        "clientInfo": {
            "type": "oauth_client_info",
            "clientId": "",
            "clientSecret":""
        }
      },
      "dynamics_365": {
        "clientInfo": {
          "type": "microsoft_oauth_client_info",
          "clientId": "",
          "clientSecret": "",
          "tenantId": ""
        }
      },
      "microsoft": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret": ""
        }
      },
      "quickbooks_online": {
        "clientInfo": {
          "type": "oauth_client_info",
          "clientId": "",
          "clientSecret": ""
        }
      }
    }
{{- end }}
