{{- if .Values.connector.credentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peaka.fullname" . }}-connection-credentials-secret
type: Opaque
stringData:
  connection_providers.json: |
    {
     {{- include "peaka.connectors.default-oauth-clients" .  | trimSuffix ","}}
    }
{{- end }}
