apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peaka.fullname" . }}-jwt-rsa-secret
type: Opaque
data:
  publickey.pem: |
    {{ .Values.jwtRsaPublicKey | b64enc | required ".Values.jwtRsaPublicKey is required!" }}
  privatekey.pem: |
    {{ .Values.jwtRsaPrivateKey | b64enc | required ".Values.jwtRsaPrivateKey is required!" }}
