apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "peaka.trino.catalog" . }}
  labels:
    app: {{ template "peaka.trino.name" . }}
    chart: {{ template "peaka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: catalogs
data:
  cat_00000000_0000_0000_0000_000000000000.properties: |
    connector.name=postgresql
    connection-url="jdbc:postgresql://{{ template "peaka.postgresql.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ template "peaka.postgresql.port" . }}/{{ template "peaka.postgresql.database" . }}"
    connection-user={{ template "peaka.postgresql.user" . }}
    connection-password={{ template "peaka.postgresql.password" . }}
    case-insensitive-name-matching=true
  cat_00000000_0000_0000_0000_000000000003.properties: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://{{ template "peaka.bigtable.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ template "peaka.bigtable.port" . }}/{{ template "peaka.bigtable.database" . }}
    connection-user={{ template "peaka.bigtable.user" . }}
    connection-password={{ template "peaka.bigtable.password" . }}
    case-insensitive-name-matching=true

  # fill below with templates
  iceberg.properties: |
    connector.name=iceberg
    hive.metastore.uri=thrift://hivemetastore-service.{{ .Release.Namespace }}.svc.cluster.local:9083
    hive.s3.path-style-access=true
    hive.s3.endpoint=http://minio.{{ .Release.Namespace }}.svc.cluster.local:9000
    hive.s3.aws-secret-key={{ .Values.trino.catalog.iceberg.s3secretKey }}
    hive.s3.aws-access-key={{ .Values.trino.catalog.iceberg.s3accessKey }}
    hive.fs.cache.max-size=100000
    iceberg.expire_snapshots.min-retention=30s
    iceberg.remove_orphan_files.min-retention=30s
