apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "peaka.trino.coordinator" . }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
