{{- if .Values.trino.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "peaka.trino.serviceAccountName" . }}
  labels:
    {{- include "peaka.trino.labels" . | nindent 4 }}
  {{- with .Values.trino.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
