apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peaka.fullname" . }}-studio-root-user-secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.rootUser.email }}
  password: {{ .Values.rootUser.password }}