apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peaka.fullname" . }}-fe-studio-app
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-fe-studio-app
    {{- include "peaka.labels" . | nindent 4 }}
data:
  default.conf: |-
    log_format time '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    '$request_time $upstream_connect_time $upstream_header_time $upstream_response_time';
    access_log  off;

    server {
      listen       80;
      server_name  localhost;
      root   /usr/share/nginx/html;

      location / {
        try_files $uri $uri/ /index.html;
      }
    
      location ~* .js$ {
          expires -1;
      }

      location ~* \.(js|css|jpg|jpeg|png|gif|ico)$ {
          # cache control with expiration date
          expires 1y;
          etag off;
          if_modified_since off;
          add_header Cache-Control "public, no-transform";
      }

      gzip on;
      gzip_disable “MSIE [1-6].(?!.*SV1)”;
      gzip_buffers 16 8k;
      gzip_proxied    no-cache no-store private expired auth;
      gzip_min_length 1000;
      gzip_types *;

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
          add_header X-Frame-Options "DENY";
      }
      add_header X-Frame-Options "DENY";
      access_log  /var/log/nginx/access.log  time;
    }
