apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "peaka.fullname" . }}-fe-studio-app
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-fe-studio-app
    {{- include "peaka.labels" . | nindent 4 }}
data:
  default.conf: |-
    {{- (tpl (.Files.Get "conf/studio-web-nginx.conf") . ) | nindent 4 }}
