apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "peaka.fullname" . }}-dbc-routes
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-dbc
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  entryPoints:
    - dbc
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      priority: 1000
      services:
        - name: {{ include "peaka.fullname" . }}-be-data-rest
          port: http
          passHostHeader: true
  {{- if .Values.tls.enabled }}
  tls:
    secretName: {{ include "peaka.fullname" . }}-tls-secret
  {{- end }}
