apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "peaka.fullname" . }}-be-workflow-history-routes
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-workflow-history
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ include "peaka.ingress.entryPoint" . }}
  routes:
    - match: Host(`{{ include "peaka.routes.baseUrl" . }}`) && PathPrefix(`/{{ include "peaka.routes.servicePath" . }}/studioapi/history`)
      kind: Rule
      priority: 10
      middlewares:
        - name: {{ include "peaka.fullname" . }}-be-workflow-history-auth-middleware
        - name: {{ include "peaka.fullname" . }}-be-workflow-history-replace-path-middleware
      services:
        - name: {{ include "peaka.fullname" . }}-be-workflow-history
          port: http
          passHostHeader: true
  {{- if .Values.tls.enabled }}
  tls:
    secretName: {{ include "peaka.fullname" . }}-tls-secret
  {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "peaka.fullname" . }}-be-workflow-history-auth-middleware
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-workflow-history
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  forwardAuth:
    address: http://{{ include "peaka.fullname" . }}-be-permission-service.{{ .Release.Namespace }}.svc.cluster.local:80/auth/workflow-history-auth-check
    authResponseHeadersRegex: ^X-Internal-Authorization-
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "peaka.fullname" . }}-be-workflow-history-replace-path-middleware
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-workflow-history
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  replacePathRegex:
    regex: ^/{{ include "peaka.routes.servicePath" . }}/studioapi/(.*)
    replacement: /(.*)