{{- if .Values.nfsServer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.name" }}-nfs-server
  namespace: {{ include "chart.namespace" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      volumes:
        - name: nfs-vol
          persistentVolumeClaim:
            claimName: nfs-vol-pvc
      restartPolicy: Always
      containers:
        - name: nfs-server
          image: itsthenetwork/nfs-server-alpine
          env:
            - name: SHARED_DIRECTORY
              value: /nfsshare
          ports:
            - name: nfs
              containerPort: 2049
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /nfsshare
              name: nfs-vol
{{- end -}}