{{- if .Values.kafkaConnect.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "peaka.kafka-connect.fullname" . }}
  labels:
    app: {{ template "peaka.kafka-connect.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: kafka-connect
      port: {{ .Values.kafkaConnect.servicePort }}
  selector:
    app: {{ template "peaka.kafka-connect.fullname" . }}
    release: {{ .Release.Name }}
{{- end }}
