apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peaka.fullname" . }}-be-collab-sharedb
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-collab-sharedb
    {{- include "peaka.labels" . | nindent 4 }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.collabSharedb.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-collab-sharedb
      {{- include "peaka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-collab-sharedb
        {{- include "peaka.labels" . | nindent 8 }}
    spec:
      containers:
        - name: collab-sharedb
          image: "{{ include "peaka.image.registry" . }}/{{ .Values.collabSharedb.image.name }}:{{ .Values.collabSharedb.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.collabSharedb.image.imagePullPolicy }}
          ports:
            - name: websocket
              containerPort: 8080
            - name: http
              containerPort: 7070
          envFrom:
            - configMapRef:
                name: {{ include "peaka.fullname" . }}-env-config
          {{- with .Values.collabSharedb.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.collabSharedb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.collabSharedb.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.cloudGateway.terminationGracePeriodSeconds }}
      {{- end }}
      {{- with .Values.collabSharedb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.collabSharedb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
