apiVersion: v1
kind: Service
metadata:
  name: {{ include "peaka.fullname" . }}-be-collab-sharedb-http
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-collab-sharedb-http
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-collab-sharedb
    {{- include "peaka.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
