apiVersion: v1
kind: Service
metadata:
  name: {{ include "peaka.fullname" . }}-be-collab-sharedb-websocket
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-collab-sharedb-websocket
    {{- include "peaka.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-be-collab-sharedb
    {{- include "peaka.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: websocket
      port: 443
      targetPort: websocket
      protocol: TCP
