apiVersion: v1
kind: Service
metadata:
  name: {{ template "peaka.hive.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "peaka.hive.name" . }}
spec:
  ports:
    - name: thrift
      port: {{ .Values.hiveMetastore.servicePort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ template "peaka.hive.name" . }}
