apiVersion: v1
kind: Service
metadata:
  name: {{ include "peaka.name" . }}-hive-metastore
  namespace: {{ include "peaka.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "peaka.name" . }}-hive-metastore
spec:
  ports:
    - name: thrift
      port: {{ .Values.hiveMetastore.servicePort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "peaka.name" . }}-hive-metastore
