apiVersion: v1
kind: Service
metadata:
  name: {{ include "peaka.name" . }}-hive-metastore
  labels:
    app.kubernetes.io/name: {{ include "peaka.name" . }}-hive-metastore
    app.kubernetes.io/component: {{ include "peaka.name" . }}-hive-metastore
    app.kubernetes.io/instance: {{ include "peaka.name" . }}-hive-metastore
spec:
  ports:
    - name: thrift
      port: {{ .Values.hiveMetastore.servicePort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "peaka.name" . }}-hive-metastore
    app.kubernetes.io/component: {{ include "peaka.name" . }}-hive-metastore
    app.kubernetes.io/instance: {{ include "peaka.name" . }}-hive-metastore
