apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/component: metastore
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/component: metastore
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ .Release.Name }}-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/component: metastore
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: metastore
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: METASTORE_DB_HOSTNAME
              value: {{ .Values.mariadb.serviceName }}
            - name: HADOOP_HEAPSIZE
              value: "{{ .Values.hadoopHeapSize }}"
            - name: METASTORE_TYPE
              value: "mysql"
          volumeMounts:
            - name: hive-config
              mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf/
      volumes:
        - name: hive-config
          configMap:
            name: {{ .Release.Name }}-config