apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "peaka.fullname" . }}-hive-metastore
  namespace: {{ include "peaka.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "peaka.fullname" . }}-hive-metastore
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "peaka.fullname" . }}-hive-metastore
  serviceName: {{ include "peaka.fullname" . }}-hive-metastore
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "peaka.fullname" . }}-hive-metastore
    spec:
      containers:
        - name: metastore
          image: "{{ .Values.hiveMetastore.image.repository }}:{{ .Values.hiveMetastore.image.tag }}"
          imagePullPolicy: {{ .Values.hiveMetastore.image.pullPolicy | quote }}
          env:
            - name: METASTORE_DB_HOSTNAME
              value: {{ .Values.mariadb.serviceName }}
            - name: HADOOP_HEAPSIZE
              value: {{ .Values.hiveMetastore.hadoopHeapSize | quote }}
            - name: METASTORE_TYPE
              value: {{ .Values.hiveMetastore.metastoreType | quote }}
          volumeMounts:
            - name: hive-config
              mountPath: /opt/apache-hive-metastore-3.0.0-bin/conf/
      volumes:
        - name: hive-config
          configMap:
            name: {{ include "peaka.fullname" . }}-hive-metastore
